spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/resume
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: resume
api:
  title: Resume #наименование приложения в документации апи (swagger)
  version: 1.0.0 #версия документации апи (swagger)